name: CI/CD y despliegue en EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Desplegar en EC2 vía SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Si no existe el proyecto, clonarlo. Si ya existe, solo hacer pull
          cd fastapi-devops || git clone https://github.com/Luchito0703/proyecticoprueba.git fastapi-devops
          cd fastapi-devops
          git pull origin main
          docker-compose down
          docker-compose up -d --build
